# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vetras
email: your-email@domain.com
description: > # this (>) means to ignore newlines until next element ("baseurl:") # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Personal website for vetras
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vetras.github.io"
twitter_username: vetrasPT
github_username:  vetras

# Build settings
markdown: kramdown
exclude: ['my-notes']
